/// Flutter icons CountersIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CountersIcons
///      fonts:
///       - asset: fonts/CountersIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CountersIcons {
  CountersIcons._();

  static const _kFontFam = 'CountersIcons';
  static const String? _kFontPkg = null;

  static const IconData clock = IconData(0xf017, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tint = IconData(0xf043, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle = IconData(0xf111, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xf185, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation_cap = IconData(0xf19d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree = IconData(0xf1bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vial = IconData(0xf492, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_five = IconData(0xf523, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_four = IconData(0xf524, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_one = IconData(0xf525, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_six = IconData(0xf526, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_three = IconData(0xf527, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_two = IconData(0xf528, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skull = IconData(0xf54c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radiation = IconData(0xf7b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire_alt = IconData(0xf7e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
